{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zerotrust.activeService" . }}
  labels:
    app: backend
    zerotrust.io/traffic: active
    {{- include "zerotrust.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.backend.globalService }}
    service.cilium.io/global: "true"
    {{- end }}
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: {{ .Values.backend.servicePort }}
      targetPort: {{ .Values.backend.listenPort }}
{{- end }}
